version: "3.9"
services:
  env:
    container_name: menu-text-detection-env
    build: 
      context: .
      dockerfile: Dockerfile

    image: ryanlinjui/menu-text-detection:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/app/.
    env_file: 
      - .env
    command: python app.py
    network_mode: bridge

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --protocol http2 run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
        - env
    network_mode: host