[tool.poetry]
name = "menu-text-detection"
version = "0.1.0"
description = ""
authors = ["ryanlinjui <ryanlinjui@gmail.com>"]
readme = "README.md"
packages = [{include = "menu_text_detection"}]

[tool.poetry.dependencies]
python = "^3.10"
google-cloud-vision = "^3.4.4"
openai = "^1.3.5"
flask = "^3.0.0"
flask-cors = "^4.0.0"
piexif = "^1.1.3"
pillow-heif = "^0.15.0"
matplotlib = "^3.8.2"
pillow = "^10.1.0"

[tool.poetry.group.dev.dependencies]
notebook = "^7.0.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
