[tool.poetry]
name = "menu-text-detection"
version = "0.1.0"
description = ""
authors = ["ryanlinjui <ryanlinjui@gmail.com>"]
readme = "README.md"
packages = [{include = "menu_text_detection"}]

[tool.poetry.dependencies]
python = "^3.10"
pytesseract = "^0.3.10"
google-cloud-vision = "^3.4.4"
openai = "^1.3.5"
flask = "^3.0.0"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
