[project]
authors = [{name = "ryanlinjui", email = "ryanlinjui@gmail.com"}]
dependencies = ["gradio>=5.26.0,<6"]
description = "Add a short description here"
name = "menu-text-detection"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.dependencies]
transformers = ">=4.51.3,<5"
notebook = ">=7.4.0,<8"
datasets = ">=3.5.0,<4"
huggingface_hub = ">=0.30.2,<0.31"
pytorch = ">=2.6.0,<3"
protobuf = ">=5.29.3,<6"
sentencepiece = ">=0.2.0,<0.3"
accelerate = ">=1.5.2,<2"
