name: Sync to Hugging Face Spaces

on:
    push:
        branches:
            - main
jobs:
    sync:
        name: Sync
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Remove bad files
              run: rm -rf examples assets

            - name: Sync to Hugging Face Spaces
              uses: JacobLinCool/huggingface-sync@v1
              with:
                  github: ${{ secrets.GITHUB_TOKEN }}
                  user: ryanlinjui # Hugging Face username or organization name
                  space: menu-text-detection # Hugging Face space name
                  token: ${{ secrets.HF_TOKEN }} # Hugging Face token